### ISSUE TITLE
brunch watch error

### ISSUE THREAD

**Issue by gtaylor** [elving/brunch-with-hipsters#11]
Just trying to do a clean install, running into an error. Disclaimer: I am a JS/brunch/Coffeescript newbie.

``` python
$ brunch w -s

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
    at startServer (/usr/local/lib/node_modules/brunch/node_modules/pushserve/index.js:51:10)
    at startServer (/usr/local/lib/node_modules/brunch/lib/watch.js:114:14)
    at /usr/local/lib/node_modules/brunch/lib/watch.js:418:18
    at /usr/local/lib/node_modules/brunch/lib/helpers.js:475:14
    at /usr/local/lib/node_modules/brunch/node_modules/read-components/index.js:220:7
    at /usr/local/lib/node_modules/brunch/node_modules/read-components/index.js:144:7
    at /usr/local/lib/node_modules/brunch/node_modules/async-each/index.js:24:44
    at /usr/local/lib/node_modules/brunch/node_modules/read-components/index.js:101:7
    at /usr/local/lib/node_modules/brunch/node_modules/read-components/index.js:49:7
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```

Any ideas?

**Comment by jacobthemyth** [comment]
EADDRINUSE means that there's something else listening on the port, I think. Brunch is on port 3333 by default, do you have another server running there?

**Comment by jacobthemyth** [comment]
Or you could just try `killall node` in case there's a zombie process running.

**Comment by gtaylor** [comment]
This is indeed the case, thanks! Closing.

**Comment by elving** [comment]
Hey @jacobthemyth, thanks for helping @gtaylor. Happy Holidays!
